# Generated by Django 2.1.1 on 2018-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180920_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
