# Generated by Django 2.1.1 on 2018-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tweet_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
