# Generated by Django 2.1.1 on 2018-10-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20180920_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='like_counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
